Implement Choose wallet screen [sc-16247]
internet-identity-labs/nfid-wallet-client pull request #2429
Opened 2024-12-15 13:42 UTC by vitaliipustovyi

2024-12-16 17:40 UTC, olsemeno commented on apps/nfid-frontend/src/features/authentication/auth-selection/passkey-flow/services.ts
> +  async getWallets() {
what is the reason to wrap function?

2024-12-16 17:42 UTC, olsemeno commented on packages/integration/src/lib/authentication/auth-state.ts
> +      email: profile.email ?? "",
please don't use empty strings. I think in ts there are 2 options: null or undefined

2024-12-16 17:44 UTC, olsemeno commented on packages/integration/src/lib/authentication/auth-state.ts
> +      email: profile.email ?? "",
and I guess it would good to filter out profiles without emails. I don't think that we have such accounts but who knows....

2024-12-17 13:40 UTC, olekid commented on apps/nfid-frontend/src/features/authentication/services.ts
> +export const setWallets = async () => {
getWallets?

2024-12-17 13:42 UTC, olekid commented on packages/ui/src/organisms/authentication/choose-wallet/index.tsx
> +  isIdentityKit,
rename to showLogo please, let parent components know it is identitykit or no

2024-12-17 13:45 UTC, olekid commented on apps/nfid-frontend/src/features/authentication/root/root-machine.ts
> +        SetWallets: {
may be something like proceedWallets with src = getWallets, sounds better

2024-12-17 13:46 UTC, olekid commented on apps/nfid-frontend/src/features/authentication/root/root-machine.ts
> +        SetWallets: {
because it's not setting anything, it tries to get them as i see in code

2024-12-17 14:02 UTC, olekid commented on packages/integration/src/lib/authentication/auth-state.ts
> +  console.log(profiles)
console.log

2024-12-17 14:05 UTC, olekid requested changes

2024-12-17 14:05 UTC, olekid commented on apps/nfid-frontend/src/features/authentication/services.ts
> +export const getWallets = async () => {
useless function

2024-12-17 14:10 UTC, olekid approved these changes

2024-12-17 17:38 UTC, olsemeno approved these changes

2024-12-17 17:51 UTC, merged